name: Terraform CI

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd Environments
          terraform init

      - name: Terraform Format Check
        run: |
          cd Environments
          terraform fmt -check -recursive

      - name: Terraform Validate
        run: |
          cd Environments
          terraform validate

      - name: Terraform Plan
        run: |
          cd Environments
          terraform plan